name: covid_overcoming
description: Support for people who used to be infected with Covid-19

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Rxdart
  # https://pub.dev/packages/rxdart
  rxdart: ^0.27.1

  # Network
  # https://pub.dev/packages/dio
  dio: ^4.0.4

  # https://pub.dev/packages/pretty_dio_logger
  pretty_dio_logger: ^1.2.0-beta-1

  # https://pub.dev/packages/retrofit
  retrofit: '>=3.0.0 <4.0.0'
  logger: any

  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.4.0

  # DI
  # https://pub.dev/packages/get_it
  get_it: ^7.2.0

  # https://pub.dev/packages/injectable
  injectable: ^1.5.3

  # State management
  # https://pub.dev/packages/flutter_bloc/install
  flutter_bloc: ^8.0.1

  # https://pub.dev/packages/equatable
  equatable: ^2.0.0

  # Support manager route for Flutter.
  # https://pub.dev/packages/fluro
  fluro: ^2.0.3

  # https://pub.dev/packages/modal_bottom_sheet
  modal_bottom_sheet: ^2.0.0

  # https://pub.dev/packages/oktoast
  oktoast: ^3.1.5

  # Utils
  # https://pub.dev/packages/permission_handler
  # permission_handler: ^8.3.0

  # https://pub.dev/packages/either_dart
  either_dart: ^0.1.4

  # https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.0.3

  # https://pub.dev/packages/keyboard_actions
  keyboard_actions: ^3.4.6

  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.13

  # https://pub.dev/packages/lint
  lint: ^1.5.3

  # https://pub.dev/packages/image_picker
  # image_picker: ^0.8.4+4

  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.0

  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.0.5

  # https://pub.dev/packages/sprintf
  sprintf: ^6.0.0

  # Support multi languages
  # https://pub.dev/packages/intl
  intl: ^0.17.0

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.0.18

  # https://github.com/Sky24n/sp_util
  sp_util: ^2.0.3

  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^1.1.0

  # https://pub.dev/packages/floor
  floor: ^1.2.0

  # https://pub.dev/packages/sqflite
  sqflite: ^2.0.2+1

  # https://pub.dev/packages/path
  path: ^1.8.0

  # https://pub.dev/packages/firebase_core
  firebase_core: ^1.19.1

  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^3.4.1

  # https://pub.dev/packages/firebase_storage
  firebase_storage: ^10.3.1

  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^3.2.1

  # https://pub.dev/packages/google_sign_in
  google_sign_in: ^5.3.3

  # https://pub.dev/packages/flutter_login_facebook
  flutter_login_facebook: ^1.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  # https://pub.dev/packages/build_runner
  build_runner:

  # Support generate for retrofit
  # https://pub.dev/packages/json_serializable
  retrofit_generator:
  json_serializable: '>4.4.0'

  # Support generate for injectable_generator
  # https://pub.dev/packages/injectable_generator
  injectable_generator:

  # https://pub.dev/packages/flutter_local_notifications/
  # flutter_local_notifications: ^9.5.0

  # https://pub.dev/packages/path_provider
  path_provider: ^2.0.9

  # https://pub.dev/packages/freezed
  freezed: ^1.0.0

  # https://pub.dev/packages/floor
  floor_generator: ^1.2.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/db/app.db

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf

flutter_intl:
  enabled: true
