name: Build Check Workflow ~ Android

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master

jobs:
  build:
    name: Build Check Workflow
    runs-on: self-hosted
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.1'
      - name: Clean project
        run: flutter clean
      - name: Get flutter dependencies.
        run: flutter pub get
      - name: Android Build Check
        run: flutter build apk --release --split-per-abi